#version 460

layout(local_size_x = 8, local_size_y = 8) in;

layout(binding = 0) uniform sampler3D  page_volumes[4];

// M8: three MRTs per holder FBO. Bindings here must match
// `src/voxel/raymarch.c3::dispatch_holder`.
layout(binding = 4, r8ui) uniform restrict writeonly uimage2D material_out;
layout(binding = 5, rg8)  uniform restrict writeonly image2D  normal_out;
// Packed `(first-hit y, column-top y)` in the same MRT. Column-top is
// the highest opaque voxel at the hit's xz — needed by the shadow
// march (heightfield comparison against wall-face first-hit y
// under-occludes, since the face entry y rises at the same rate as
// the sun ray). Packed together here so the deferred pass's per-
// holder sampler count stays at 48 rather than 64 (over the fragment
// sampler cap on GPUs with MAX_TEXTURE_IMAGE_UNITS = 32).
layout(binding = 6, rg16f) uniform restrict writeonly image2D height_out;

layout(std140, binding = 7) uniform U {
    vec4  holder_center;                // (cx, 0, cz, 0)
    vec4  iso_bbox;                     // (sx_min, sy_min, sx_max, sy_max) in holder-local iso
    vec4  page_world_min[4];
    vec4  page_world_max[4];
    ivec4 resolution;                   // fbo_w, fbo_h, volume_pitch, 0
    ivec4 page_valid_mask;              // bit i: page i resident
    float iso_tilt;
    float volume_max_y;
    float voxel_len;                    // world units per voxel (= holder_extent / volume_pitch)
    float _pad0;
};

// Normals volume: parallel to `page_volumes`. Sampled at the winning voxel's
// uvw to recover the octahedral-packed surface normal generated by
// generate_normal.comp.glsl. Bindings 8..11 were picked to stay clear of the
// UBO at binding 7.
layout(binding = 8) uniform sampler3D page_normals[4];

const int MAX_STEPS = 1024;

vec2 aabb_intersect(vec3 ro, vec3 rd, vec3 bmin, vec3 bmax)
{
    vec3 inv = 1.0 / rd;
    vec3 t0  = (bmin - ro) * inv;
    vec3 t1  = (bmax - ro) * inv;
    vec3 tmn = min(t0, t1);
    vec3 tmx = max(t0, t1);
    float tn = max(max(tmn.x, tmn.y), tmn.z);
    float tf = min(min(tmx.x, tmx.y), tmx.z);
    return vec2(tn, tf);
}

vec4 sample_page(int i, vec3 uvw)
{
    // Unroll: sampler array indexing must be a dynamically uniform or
    // constant expression. A switch on (0..3) is safe here.
    switch (i) {
        case 0: return texture(page_volumes[0], uvw);
        case 1: return texture(page_volumes[1], uvw);
        case 2: return texture(page_volumes[2], uvw);
        default: return texture(page_volumes[3], uvw);
    }
}

vec2 sample_normal(int i, vec3 uvw)
{
    switch (i) {
        case 0: return texture(page_normals[0], uvw).rg;
        case 1: return texture(page_normals[1], uvw).rg;
        case 2: return texture(page_normals[2], uvw).rg;
        default: return texture(page_normals[3], uvw).rg;
    }
}

void main()
{
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    if (pix.x >= resolution.x || pix.y >= resolution.y) return;

    float T = iso_tilt;

    // pixel → iso-space (holder-local)
    float frac_u = (float(pix.x) + 0.5) / float(resolution.x);
    float frac_v = (float(pix.y) + 0.5) / float(resolution.y);
    float sx = mix(iso_bbox.x, iso_bbox.z, frac_u);
    float sy = mix(iso_bbox.y, iso_bbox.w, frac_v);

    // y-up sy convention: sy = T*(dx+dz) + wy. Solve for (dx+dz) at the ray's
    // starting plane y = y_start (top of holder volume). Ray still marches
    // downward — rd.y < 0, camera above, y_start at the top face — so corner
    // pixels outside the iso parallelogram originate at/outside the volume
    // in XZ and grazing-miss in aabb_intersect. A prior attempt flipped the
    // ray to start at y=0 and march upward; that made the ground voxel the
    // first opaque hit for every pixel and painted terrain as a solid slab.
    float y_start = volume_max_y;
    float sum     = (sy - y_start) / T;         // dx + dz
    float diff    = sx;                          // dx - dz
    float dx0     = 0.5 * (diff + sum);
    float dz0     = 0.5 * (sum  - diff);

    vec3 ro = vec3(holder_center.x + dx0, y_start, holder_center.z + dz0);
    vec3 rd = normalize(vec3(1.0, -2.0 * T, 1.0));

    bool  hit      = false;
    uint  hit_mat  = 0u;
    vec2  hit_norm = vec2(0.5, 0.5);     // octahedral pack of +z
    float hit_y    = -1.0e30;

    // Intersect ray with each page AABB; march in near-to-far order.
    // 4 pages → 4 entries. Sort by tn via simple insertion.
    float tns[4];
    float tfs[4];
    int   order[4] = int[4](0, 1, 2, 3);
    for (int i = 0; i < 4; i++) {
        uint valid = uint(page_valid_mask.x);
        if ((valid & (1u << i)) == 0u) {
            tns[i] = 1.0e30;
            tfs[i] = 1.0e30;
        } else {
            vec2 t = aabb_intersect(ro, rd, page_world_min[i].xyz, page_world_max[i].xyz);
            if (t.y > max(t.x, 0.0)) {
                tns[i] = max(t.x, 0.0);
                tfs[i] = t.y;
            } else {
                tns[i] = 1.0e30;
                tfs[i] = 1.0e30;
            }
        }
    }
    // Insertion sort (4 entries)
    for (int i = 1; i < 4; i++) {
        int k = order[i];
        int j = i - 1;
        while (j >= 0 && tns[order[j]] > tns[k]) {
            order[j + 1] = order[j];
            j--;
        }
        order[j + 1] = k;
    }

    int steps_remaining = MAX_STEPS;
    bool done = false;
    int  hit_page = 0;
    vec3 hit_wp   = vec3(0.0);
    float col_top = -1.0e30;

    for (int slot = 0; slot < 4 && !done; slot++) {
        int p = order[slot];
        if (tns[p] >= 1.0e29) break;   // no more valid pages

        float t_cur = tns[p];
        float t_end = tfs[p];
        vec3  pmin  = page_world_min[p].xyz;
        vec3  pmax  = page_world_max[p].xyz;
        vec3  psize = pmax - pmin;

        while (t_cur < t_end && steps_remaining > 0) {
            vec3 wp  = ro + t_cur * rd;
            vec3 uvw = (wp - pmin) / psize;
            vec4 v   = sample_page(p, uvw);
            if (v.a > 0.5) {
                hit      = true;
                hit_mat  = uint(int(v.b * 255.0 + 0.5));
                hit_norm = sample_normal(p, uvw);
                hit_y    = wp.y;
                hit_page = p;
                hit_wp   = wp;
                done     = true;
                break;
            }
            t_cur += voxel_len;
            steps_remaining--;
        }
    }

    // Column-top scan: walk straight up from the first hit at its xz,
    // tracking the highest opaque voxel. Must tolerate short air streaks:
    // building walls are emitted as 3 stacked superellipsoids (half_y=4,
    // p=4 each), and at off-center columns (d.x != 0) the k-level seams
    // at y = 40, 48 produce SINGLE-VOXEL air gaps (d.x⁴ + d.y⁴ > 1 right
    // at the boundary in both adjacent k-levels). A "break on first air"
    // scan capped col_top at ~y=47 for every off-center wall pixel —
    // the exact visible-wall-face case — so ground shadows from
    // buildings never registered. Tree canopies (solid spheres, no gaps)
    // and centre wall columns (d.x=0) happened to work.
    //
    // MAX_AIR_STREAK = 4 covers any 1-voxel wall seam with slack to
    // spare; genuine top-of-column (canopy/roof/ground → open sky above)
    // still triggers the break after 4 air voxels.
    if (hit) {
        vec3  pmin_h  = page_world_min[hit_page].xyz;
        vec3  pmax_h  = page_world_max[hit_page].xyz;
        vec3  psize_h = pmax_h - pmin_h;
        col_top = hit_y;
        int air_streak = 0;
        const int MAX_AIR_STREAK = 4;
        for (int k = 1; k < 128; k++) {
            vec3 up_wp = vec3(hit_wp.x, hit_wp.y + float(k) * voxel_len, hit_wp.z);
            if (up_wp.y >= pmax_h.y) break;
            vec3 up_uvw = (up_wp - pmin_h) / psize_h;
            if (any(lessThan(up_uvw, vec3(0.0))) || any(greaterThan(up_uvw, vec3(1.0)))) break;
            vec4 up_v = sample_page(hit_page, up_uvw);
            if (up_v.a < 0.5) {
                air_streak++;
                if (air_streak > MAX_AIR_STREAK) break;
            } else {
                air_streak = 0;
                col_top = up_wp.y;
            }
        }
    }

    if (!hit) {
        imageStore(material_out, pix, uvec4(0));
        imageStore(normal_out,   pix, vec4(0.5, 0.5, 0.0, 0.0));
        imageStore(height_out,   pix, vec4(-1.0e30, -1.0e30, 0.0, 0.0));
    } else {
        imageStore(material_out, pix, uvec4(hit_mat, 0u, 0u, 0u));
        imageStore(normal_out,   pix, vec4(hit_norm, 0.0, 0.0));
        imageStore(height_out,   pix, vec4(hit_y, col_top, 0.0, 0.0));
    }
}
