#version 460

layout(local_size_x = 8, local_size_y = 8) in;

layout(binding = 0) uniform sampler3D  page_volumes[4];

// M8: three MRTs per holder FBO. Bindings here must match
// `src/voxel/raymarch.c3::dispatch_holder`.
layout(binding = 4, r8ui) uniform restrict writeonly uimage2D material_out;
layout(binding = 5, rg8)  uniform restrict writeonly image2D  normal_out;
layout(binding = 6, r16f) uniform restrict writeonly image2D  height_out;

layout(std140, binding = 7) uniform U {
    vec4  holder_center;                // (cx, 0, cz, 0)
    vec4  iso_bbox;                     // (sx_min, sy_min, sx_max, sy_max) in holder-local iso
    vec4  page_world_min[4];
    vec4  page_world_max[4];
    ivec4 resolution;                   // fbo_w, fbo_h, volume_pitch, 0
    ivec4 page_valid_mask;              // bit i: page i resident
    float iso_tilt;
    float volume_max_y;
    float voxel_len;                    // world units per voxel (= holder_extent / volume_pitch)
    float _pad0;
};

// Normals volume: parallel to `page_volumes`. Sampled at the winning voxel's
// uvw to recover the octahedral-packed surface normal generated by
// generate_normal.comp.glsl. Bindings 8..11 were picked to stay clear of the
// UBO at binding 7.
layout(binding = 8) uniform sampler3D page_normals[4];

const int MAX_STEPS = 1024;

vec2 aabb_intersect(vec3 ro, vec3 rd, vec3 bmin, vec3 bmax)
{
    vec3 inv = 1.0 / rd;
    vec3 t0  = (bmin - ro) * inv;
    vec3 t1  = (bmax - ro) * inv;
    vec3 tmn = min(t0, t1);
    vec3 tmx = max(t0, t1);
    float tn = max(max(tmn.x, tmn.y), tmn.z);
    float tf = min(min(tmx.x, tmx.y), tmx.z);
    return vec2(tn, tf);
}

vec4 sample_page(int i, vec3 uvw)
{
    // Unroll: sampler array indexing must be a dynamically uniform or
    // constant expression. A switch on (0..3) is safe here.
    switch (i) {
        case 0: return texture(page_volumes[0], uvw);
        case 1: return texture(page_volumes[1], uvw);
        case 2: return texture(page_volumes[2], uvw);
        default: return texture(page_volumes[3], uvw);
    }
}

vec2 sample_normal(int i, vec3 uvw)
{
    switch (i) {
        case 0: return texture(page_normals[0], uvw).rg;
        case 1: return texture(page_normals[1], uvw).rg;
        case 2: return texture(page_normals[2], uvw).rg;
        default: return texture(page_normals[3], uvw).rg;
    }
}

void main()
{
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    if (pix.x >= resolution.x || pix.y >= resolution.y) return;

    float T = iso_tilt;

    // pixel → iso-space (holder-local)
    float frac_u = (float(pix.x) + 0.5) / float(resolution.x);
    float frac_v = (float(pix.y) + 0.5) / float(resolution.y);
    float sx = mix(iso_bbox.x, iso_bbox.z, frac_u);
    float sy = mix(iso_bbox.y, iso_bbox.w, frac_v);

    // y-up sy convention: sy = T*(dx+dz) + wy. Solve for (dx+dz) at the ray's
    // starting plane y = y_start (top of holder volume). Ray still marches
    // downward — rd.y < 0, camera above, y_start at the top face — so corner
    // pixels outside the iso parallelogram originate at/outside the volume
    // in XZ and grazing-miss in aabb_intersect. A prior attempt flipped the
    // ray to start at y=0 and march upward; that made the ground voxel the
    // first opaque hit for every pixel and painted terrain as a solid slab.
    float y_start = volume_max_y;
    float sum     = (sy - y_start) / T;         // dx + dz
    float diff    = sx;                          // dx - dz
    float dx0     = 0.5 * (diff + sum);
    float dz0     = 0.5 * (sum  - diff);

    vec3 ro = vec3(holder_center.x + dx0, y_start, holder_center.z + dz0);
    vec3 rd = normalize(vec3(1.0, -2.0 * T, 1.0));

    bool  hit      = false;
    uint  hit_mat  = 0u;
    vec2  hit_norm = vec2(0.5, 0.5);     // octahedral pack of +z
    float hit_y    = -1.0e30;

    // Intersect ray with each page AABB; march in near-to-far order.
    // 4 pages → 4 entries. Sort by tn via simple insertion.
    float tns[4];
    float tfs[4];
    int   order[4] = int[4](0, 1, 2, 3);
    for (int i = 0; i < 4; i++) {
        uint valid = uint(page_valid_mask.x);
        if ((valid & (1u << i)) == 0u) {
            tns[i] = 1.0e30;
            tfs[i] = 1.0e30;
        } else {
            vec2 t = aabb_intersect(ro, rd, page_world_min[i].xyz, page_world_max[i].xyz);
            if (t.y > max(t.x, 0.0)) {
                tns[i] = max(t.x, 0.0);
                tfs[i] = t.y;
            } else {
                tns[i] = 1.0e30;
                tfs[i] = 1.0e30;
            }
        }
    }
    // Insertion sort (4 entries)
    for (int i = 1; i < 4; i++) {
        int k = order[i];
        int j = i - 1;
        while (j >= 0 && tns[order[j]] > tns[k]) {
            order[j + 1] = order[j];
            j--;
        }
        order[j + 1] = k;
    }

    int steps_remaining = MAX_STEPS;
    bool done = false;
    int  hit_page = 0;
    vec3 hit_wp   = vec3(0.0);

    for (int slot = 0; slot < 4 && !done; slot++) {
        int p = order[slot];
        if (tns[p] >= 1.0e29) break;   // no more valid pages

        float t_cur = tns[p];
        float t_end = tfs[p];
        vec3  pmin  = page_world_min[p].xyz;
        vec3  pmax  = page_world_max[p].xyz;
        vec3  psize = pmax - pmin;

        while (t_cur < t_end && steps_remaining > 0) {
            vec3 wp  = ro + t_cur * rd;
            vec3 uvw = (wp - pmin) / psize;
            vec4 v   = sample_page(p, uvw);
            if (v.a > 0.5) {
                hit      = true;
                hit_mat  = uint(int(v.b * 255.0 + 0.5));
                hit_norm = sample_normal(p, uvw);
                hit_y    = wp.y;
                hit_page = p;
                hit_wp   = wp;
                done     = true;
                break;
            }
            t_cur += voxel_len;
            steps_remaining--;
        }
    }

    // Column-max scan. The iso ray's first-hit y is a *surface* value —
    // for a visible wall face or tree trunk it sits midway up the column,
    // not at the column top. The heightfield shadow test in lighting.frag
    // compares against this height; if it's a mid-column value, walls
    // under-occlude and their ground shadows vanish. Scan straight up in
    // the hit's page at the hit's xz and keep the highest opaque y —
    // that's the tallest thing in the column for shadow-casting purposes.
    // Stays within one page (page is 128 world units wide/tall in xz and
    // 128 in y, one page per column position).
    if (hit) {
        vec3  pmin_h  = page_world_min[hit_page].xyz;
        vec3  pmax_h  = page_world_max[hit_page].xyz;
        vec3  psize_h = pmax_h - pmin_h;
        float col_max = hit_y;
        for (float cy = volume_max_y - 0.5; cy > hit_y + 0.5; cy -= 1.0) {
            vec3 q_wp  = vec3(hit_wp.x, cy, hit_wp.z);
            vec3 q_uvw = (q_wp - pmin_h) / psize_h;
            if (any(lessThan(q_uvw, vec3(0.0))) || any(greaterThan(q_uvw, vec3(1.0)))) continue;
            vec4 qv = sample_page(hit_page, q_uvw);
            if (qv.a > 0.5) { col_max = cy; break; }
        }
        hit_y = col_max;
    }

    if (!hit) {
        imageStore(material_out, pix, uvec4(0));
        imageStore(normal_out,   pix, vec4(0.5, 0.5, 0.0, 0.0));
        imageStore(height_out,   pix, vec4(-1.0e30, 0.0, 0.0, 0.0));
    } else {
        imageStore(material_out, pix, uvec4(hit_mat, 0u, 0u, 0u));
        imageStore(normal_out,   pix, vec4(hit_norm, 0.0, 0.0));
        imageStore(height_out,   pix, vec4(hit_y, 0.0, 0.0, 0.0));
    }
}
